//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("quizData", Namespace="", IsNullable=false)]
public partial class XmlQuizData {
    
    private XmlParameters parametersField;
    
    private XmlTypeDefinition typeDefinitionsField;
    
    private XmlElement[] elementListField;
    
    private XmlQuestionCategories questionCategoriesField;
    
    /// <remarks/>
    public XmlParameters parameters {
        get {
            return this.parametersField;
        }
        set {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    public XmlTypeDefinition typeDefinitions {
        get {
            return this.typeDefinitionsField;
        }
        set {
            this.typeDefinitionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("element", IsNullable=false)]
    public XmlElement[] elementList {
        get {
            return this.elementListField;
        }
        set {
            this.elementListField = value;
        }
    }
    
    /// <remarks/>
    public XmlQuestionCategories questionCategories {
        get {
            return this.questionCategoriesField;
        }
        set {
            this.questionCategoriesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlParameters {
    
    private XmlLanguage[] languageListField;
    
    private XmlName[] questionnaireNameField;
    
    private XmlLevel[] levelListField;
    
    private string questionnaireIdField;
    
    private string logFileNameField;
    
    private XmlLogLevelEnum fileLogLevelField;
    
    private XmlLogLevelEnum consoleLogLevelField;
    
    private string databaseNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("language", IsNullable=false)]
    public XmlLanguage[] languageList {
        get {
            return this.languageListField;
        }
        set {
            this.languageListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("name", IsNullable=false)]
    public XmlName[] questionnaireName {
        get {
            return this.questionnaireNameField;
        }
        set {
            this.questionnaireNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("level", IsNullable=false)]
    public XmlLevel[] levelList {
        get {
            return this.levelListField;
        }
        set {
            this.levelListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string questionnaireId {
        get {
            return this.questionnaireIdField;
        }
        set {
            this.questionnaireIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string logFileName {
        get {
            return this.logFileNameField;
        }
        set {
            this.logFileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public XmlLogLevelEnum fileLogLevel {
        get {
            return this.fileLogLevelField;
        }
        set {
            this.fileLogLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public XmlLogLevelEnum consoleLogLevel {
        get {
            return this.consoleLogLevelField;
        }
        set {
            this.consoleLogLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string databaseName {
        get {
            return this.databaseNameField;
        }
        set {
            this.databaseNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlLanguage {
    
    private XmlLanguageId idField;
    
    private string nameField;
    
    private XmlLanguageStatusEnum statusField;
    
    private bool statusFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public XmlLanguageId id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public XmlLanguageStatusEnum status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
public enum XmlLanguageId {
    
    /// <remarks/>
    fr,
    
    /// <remarks/>
    en,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
public enum XmlLanguageStatusEnum {
    
    /// <remarks/>
    TRANSLATION_COMPLETED,
    
    /// <remarks/>
    TRANSLATION_IN_PROGRESS,
    
    /// <remarks/>
    IGNORE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlQuestionText {
    
    private XmlLanguageIdRef languageField;
    
    private string textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public XmlLanguageIdRef language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
public enum XmlLanguageIdRef {
    
    /// <remarks/>
    fr,
    
    /// <remarks/>
    en,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlAttributeQuestionCategory {
    
    private XmlQuestionText[] questionTextField;
    
    private string elementTypeField;
    
    private string questionAttributeField;
    
    private string answerAttributeField;
    
    private XmlAnswerProximityCriterionEnum answerProximityCriterionField;
    
    private double distribParameterCorrectionField;
    
    private bool distribParameterCorrectionFieldSpecified;
    
    private XmlCommentModeEnum commentModeField;
    
    private string weightField;
    
    private string minLevelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("questionText")]
    public XmlQuestionText[] questionText {
        get {
            return this.questionTextField;
        }
        set {
            this.questionTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string elementType {
        get {
            return this.elementTypeField;
        }
        set {
            this.elementTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string questionAttribute {
        get {
            return this.questionAttributeField;
        }
        set {
            this.questionAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string answerAttribute {
        get {
            return this.answerAttributeField;
        }
        set {
            this.answerAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public XmlAnswerProximityCriterionEnum answerProximityCriterion {
        get {
            return this.answerProximityCriterionField;
        }
        set {
            this.answerProximityCriterionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double distribParameterCorrection {
        get {
            return this.distribParameterCorrectionField;
        }
        set {
            this.distribParameterCorrectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool distribParameterCorrectionSpecified {
        get {
            return this.distribParameterCorrectionFieldSpecified;
        }
        set {
            this.distribParameterCorrectionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public XmlCommentModeEnum commentMode {
        get {
            return this.commentModeField;
        }
        set {
            this.commentModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string minLevel {
        get {
            return this.minLevelField;
        }
        set {
            this.minLevelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
public enum XmlAnswerProximityCriterionEnum {
    
    /// <remarks/>
    ATTRIBUTE_VALUE_AS_NUMBER,
    
    /// <remarks/>
    SORT_KEY,
    
    /// <remarks/>
    ELEMENT_LOCATION,
    
    /// <remarks/>
    NONE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
public enum XmlCommentModeEnum {
    
    /// <remarks/>
    QUESTION_ATTRIBUTE,
    
    /// <remarks/>
    NAME,
    
    /// <remarks/>
    NONE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlQuestionCategories {
    
    private XmlAttributeQuestionCategory[] attributeQuestionCategoryListField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("attributeQuestionCategory", IsNullable=false)]
    public XmlAttributeQuestionCategory[] attributeQuestionCategoryList {
        get {
            return this.attributeQuestionCategoryListField;
        }
        set {
            this.attributeQuestionCategoryListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlRelation {
    
    private string typeField;
    
    private string linkedElementField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string linkedElement {
        get {
            return this.linkedElementField;
        }
        set {
            this.linkedElementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlNumericalAttribute {
    
    private string typeField;
    
    private double valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlAttributeValue {
    
    private XmlLanguageIdRef languageField;
    
    private string valueField;
    
    private string commentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public XmlLanguageIdRef language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlAttribute {
    
    private XmlAttributeValue[] valueField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("value")]
    public XmlAttributeValue[] value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlElement {
    
    private XmlName[] elementNameField;
    
    private XmlAttribute[] attributeListField;
    
    private XmlNumericalAttribute[] numericalAttributeListField;
    
    private XmlRelation[] relationListField;
    
    private string idField;
    
    private string typeField;
    
    private string minLevelField;
    
    private string sortKeyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("name", IsNullable=false)]
    public XmlName[] elementName {
        get {
            return this.elementNameField;
        }
        set {
            this.elementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("attribute", IsNullable=false)]
    public XmlAttribute[] attributeList {
        get {
            return this.attributeListField;
        }
        set {
            this.attributeListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("numericalAttribute", IsNullable=false)]
    public XmlNumericalAttribute[] numericalAttributeList {
        get {
            return this.numericalAttributeListField;
        }
        set {
            this.numericalAttributeListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("relation", IsNullable=false)]
    public XmlRelation[] relationList {
        get {
            return this.relationListField;
        }
        set {
            this.relationListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string minLevel {
        get {
            return this.minLevelField;
        }
        set {
            this.minLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sortKey {
        get {
            return this.sortKeyField;
        }
        set {
            this.sortKeyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlName {
    
    private XmlLanguageIdRef languageField;
    
    private string textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public XmlLanguageIdRef language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlRelationNNType {
    
    private string idField;
    
    private string startTypeField;
    
    private string endTypeField;
    
    private XmlCheckSymetryEnum checkSymetryField;
    
    private bool checkSymetryFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string startType {
        get {
            return this.startTypeField;
        }
        set {
            this.startTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string endType {
        get {
            return this.endTypeField;
        }
        set {
            this.endTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public XmlCheckSymetryEnum checkSymetry {
        get {
            return this.checkSymetryField;
        }
        set {
            this.checkSymetryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool checkSymetrySpecified {
        get {
            return this.checkSymetryFieldSpecified;
        }
        set {
            this.checkSymetryFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
public enum XmlCheckSymetryEnum {
    
    /// <remarks/>
    NO,
    
    /// <remarks/>
    YES_WARNING,
    
    /// <remarks/>
    YES_ERROR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlRelation1NType {
    
    private string idField;
    
    private string startTypeField;
    
    private string endTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string startType {
        get {
            return this.startTypeField;
        }
        set {
            this.startTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string endType {
        get {
            return this.endTypeField;
        }
        set {
            this.endTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlRelation11Type {
    
    private string idField;
    
    private string startTypeField;
    
    private string endTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string startType {
        get {
            return this.startTypeField;
        }
        set {
            this.startTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string endType {
        get {
            return this.endTypeField;
        }
        set {
            this.endTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlNumericalAttributeType {
    
    private string idField;
    
    private string unitField;
    
    private double ambiguityThresholdField;
    
    private string displayPrecisionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double ambiguityThreshold {
        get {
            return this.ambiguityThresholdField;
        }
        set {
            this.ambiguityThresholdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string displayPrecision {
        get {
            return this.displayPrecisionField;
        }
        set {
            this.displayPrecisionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlAttributeType {
    
    private string idField;
    
    private bool canBeQuestionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool canBeQuestion {
        get {
            return this.canBeQuestionField;
        }
        set {
            this.canBeQuestionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlElementType {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlTypeDefinition {
    
    private XmlElementType[] elementTypeListField;
    
    private XmlAttributeType[] attributeTypeListField;
    
    private XmlNumericalAttributeType[] numericalAttributeTypeListField;
    
    private XmlRelation11Type[] relation11TypeListField;
    
    private XmlRelation1NType[] relation1NTypeListField;
    
    private XmlRelationNNType[] relationNNTypeListField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("elementType", IsNullable=false)]
    public XmlElementType[] elementTypeList {
        get {
            return this.elementTypeListField;
        }
        set {
            this.elementTypeListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("attributeType", IsNullable=false)]
    public XmlAttributeType[] attributeTypeList {
        get {
            return this.attributeTypeListField;
        }
        set {
            this.attributeTypeListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("numericalAttributeType", IsNullable=false)]
    public XmlNumericalAttributeType[] numericalAttributeTypeList {
        get {
            return this.numericalAttributeTypeListField;
        }
        set {
            this.numericalAttributeTypeListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("relation11Type", IsNullable=false)]
    public XmlRelation11Type[] relation11TypeList {
        get {
            return this.relation11TypeListField;
        }
        set {
            this.relation11TypeListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("relation1NType", IsNullable=false)]
    public XmlRelation1NType[] relation1NTypeList {
        get {
            return this.relation1NTypeListField;
        }
        set {
            this.relation1NTypeListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("relationNNType", IsNullable=false)]
    public XmlRelationNNType[] relationNNTypeList {
        get {
            return this.relationNNTypeListField;
        }
        set {
            this.relationNNTypeListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlLevel {
    
    private XmlName[] nameField;
    
    private string levelIdField;
    
    private string valueField;
    
    private string choiceCountField;
    
    private string questionCountField;
    
    private double distribParameterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("name")]
    public XmlName[] name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string levelId {
        get {
            return this.levelIdField;
        }
        set {
            this.levelIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string choiceCount {
        get {
            return this.choiceCountField;
        }
        set {
            this.choiceCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string questionCount {
        get {
            return this.questionCountField;
        }
        set {
            this.questionCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double distribParameter {
        get {
            return this.distribParameterField;
        }
        set {
            this.distribParameterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
public enum XmlLogLevelEnum {
    
    /// <remarks/>
    NO_LOG,
    
    /// <remarks/>
    ERROR,
    
    /// <remarks/>
    WARNING,
    
    /// <remarks/>
    MESSAGE,
}
