/* --------------------------------------------------------------------
 *
 * Copyright (C) 2018
 *
 * This file is part of the Diaphnea project.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License
 * version 3 as published by the Free Software Foundation
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * -------------------------------------------------------------------- */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
public partial class kml {
    
    private kmlGroundOverlay groundOverlayField;
    
    /// <remarks/>
    public kmlGroundOverlay GroundOverlay {
        get {
            return this.groundOverlayField;
        }
        set {
            this.groundOverlayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
public partial class kmlGroundOverlay {
    
    private string nameField;
    
    private kmlGroundOverlayIcon iconField;
    
    private kmlGroundOverlayLatLonBox latLonBoxField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public kmlGroundOverlayIcon Icon {
        get {
            return this.iconField;
        }
        set {
            this.iconField = value;
        }
    }
    
    /// <remarks/>
    public kmlGroundOverlayLatLonBox LatLonBox {
        get {
            return this.latLonBoxField;
        }
        set {
            this.latLonBoxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
public partial class kmlGroundOverlayIcon {
    
    private string hrefField;
    
    private double viewBoundScaleField;
    
    /// <remarks/>
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    public double viewBoundScale {
        get {
            return this.viewBoundScaleField;
        }
        set {
            this.viewBoundScaleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
public partial class kmlGroundOverlayLatLonBox {
    
    private double northField;
    
    private double southField;
    
    private double eastField;
    
    private double westField;
    
    /// <remarks/>
    public double north {
        get {
            return this.northField;
        }
        set {
            this.northField = value;
        }
    }
    
    /// <remarks/>
    public double south {
        get {
            return this.southField;
        }
        set {
            this.southField = value;
        }
    }
    
    /// <remarks/>
    public double east {
        get {
            return this.eastField;
        }
        set {
            this.eastField = value;
        }
    }
    
    /// <remarks/>
    public double west {
        get {
            return this.westField;
        }
        set {
            this.westField = value;
        }
    }
}
