#pragma once

namespace map_server
{
	enum ErrorEnum
	{
        MONGO_CLIENT_INIT_FAILED = 0,
        MONGO_CLIENT_SHUTDOWN_FAILED = 1,
        DATABASE_SERVER_CONNECTION_FAILED = 2,
        BAD_DATABASE_CONTENT = 3,
		EMPTY_REQUEST = 4,
		NO_REQUEST_ID = 5,
		NO_REQUEST_TYPE = 6,
		BAD_REQUEST_TYPE = 8,
		NOT_ENOUGH_TOKENS = 8,
		BAD_PARAMETER = 9,
		UNKNOWN_ID = 10
	};
}
