#pragma once

namespace map_server
{
	enum ErrorEnum
	{
		UNHANDLED_EXCEPTION = 0,
        MONGO_CLIENT_INIT_FAILED = 1,
        MONGO_CLIENT_SHUTDOWN_FAILED = 2,
        DATABASE_SERVER_CONNECTION_FAILED = 3,
        BAD_DATABASE_CONTENT = 4,
		EMPTY_REQUEST = 5,
		NO_REQUEST_ID = 6,
		NO_REQUEST_TYPE = 7,
		BAD_REQUEST_TYPE = 8,
		NOT_ENOUGH_TOKENS = 9,
		BAD_PARAMETER = 10,
		UNKNOWN_ID = 11
	};
}
