//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Ce code source a été automatiquement généré par xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("mapData", Namespace="", IsNullable=false)]
public partial class XmlMapData {
    
    private XmlParameters parametersField;
    
    private XmlResolution[] resolutionListField;
    
    private XmlLookList lookListField;
    
    private XmlElementList elementListField;
    
    /// <remarks/>
    public XmlParameters parameters {
        get {
            return this.parametersField;
        }
        set {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("resolution", IsNullable=false)]
    public XmlResolution[] resolutionList {
        get {
            return this.resolutionListField;
        }
        set {
            this.resolutionListField = value;
        }
    }
    
    /// <remarks/>
    public XmlLookList lookList {
        get {
            return this.lookListField;
        }
        set {
            this.lookListField = value;
        }
    }
    
    /// <remarks/>
    public XmlElementList elementList {
        get {
            return this.elementListField;
        }
        set {
            this.elementListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlParameters {
    
    private string logFileNameField;
    
    private XmlLogLevelEnum fileLogLevelField;
    
    private XmlLogLevelEnum consoleLogLevelField;
    
    private string databaseNameField;
    
    private string kmlDirField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string logFileName {
        get {
            return this.logFileNameField;
        }
        set {
            this.logFileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public XmlLogLevelEnum fileLogLevel {
        get {
            return this.fileLogLevelField;
        }
        set {
            this.fileLogLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public XmlLogLevelEnum consoleLogLevel {
        get {
            return this.consoleLogLevelField;
        }
        set {
            this.consoleLogLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string databaseName {
        get {
            return this.databaseNameField;
        }
        set {
            this.databaseNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string kmlDir {
        get {
            return this.kmlDirField;
        }
        set {
            this.kmlDirField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
public enum XmlLogLevelEnum {
    
    /// <remarks/>
    NO_LOG,
    
    /// <remarks/>
    ERROR,
    
    /// <remarks/>
    WARNING,
    
    /// <remarks/>
    MESSAGE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlPointElement {
    
    private string idField;
    
    private string nameField;
    
    private string shortNameField;
    
    private string lookField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shortName {
        get {
            return this.shortNameField;
        }
        set {
            this.shortNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string look {
        get {
            return this.lookField;
        }
        set {
            this.lookField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlLineElement {
    
    private string idField;
    
    private string nameField;
    
    private string shortNameField;
    
    private string lookField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shortName {
        get {
            return this.shortNameField;
        }
        set {
            this.shortNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string look {
        get {
            return this.lookField;
        }
        set {
            this.lookField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlPolygonElement {
    
    private string idField;
    
    private string nameField;
    
    private string shortNameField;
    
    private string lookField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shortName {
        get {
            return this.shortNameField;
        }
        set {
            this.shortNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string look {
        get {
            return this.lookField;
        }
        set {
            this.lookField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlElementList {
    
    private XmlPolygonElement[] polygonElementListField;
    
    private XmlLineElement[] lineElementListField;
    
    private XmlPointElement[] pointElementListField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("polygonElement", IsNullable=false)]
    public XmlPolygonElement[] polygonElementList {
        get {
            return this.polygonElementListField;
        }
        set {
            this.polygonElementListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("lineElement", IsNullable=false)]
    public XmlLineElement[] lineElementList {
        get {
            return this.lineElementListField;
        }
        set {
            this.lineElementListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("pointElement", IsNullable=false)]
    public XmlPointElement[] pointElementList {
        get {
            return this.pointElementListField;
        }
        set {
            this.pointElementListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlPointLook {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlLineLook {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlPolygonLook {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlLookList {
    
    private XmlPolygonLook[] polygonLookListField;
    
    private XmlLineLook[] lineLookListField;
    
    private XmlPointLook[] pointLookListField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("polygonLook", IsNullable=false)]
    public XmlPolygonLook[] polygonLookList {
        get {
            return this.polygonLookListField;
        }
        set {
            this.polygonLookListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("lineLook", IsNullable=false)]
    public XmlLineLook[] lineLookList {
        get {
            return this.lineLookListField;
        }
        set {
            this.lineLookListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("pointLook", IsNullable=false)]
    public XmlPointLook[] pointLookList {
        get {
            return this.pointLookListField;
        }
        set {
            this.pointLookListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlResolution {
    
    private string outputDirField;
    
    private double sampleLength1Field;
    
    private string sampleRatioField;
    
    private string smoothingWidthField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string outputDir {
        get {
            return this.outputDirField;
        }
        set {
            this.outputDirField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double sampleLength1 {
        get {
            return this.sampleLength1Field;
        }
        set {
            this.sampleLength1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string sampleRatio {
        get {
            return this.sampleRatioField;
        }
        set {
            this.sampleRatioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string smoothingWidth {
        get {
            return this.smoothingWidthField;
        }
        set {
            this.smoothingWidthField = value;
        }
    }
}
